name: 'Run regression tests'

on:
  workflow_dispatch:
    inputs:
      selected_suite:
        description: 'Select the suite to execute'
        required: false
        default: 'login catalog cart'
        type: string
      operating_system:
        description: 'Select the OS'
        required: true
        default: 'android'
        type: choice
        options:
          - android
          - ios

env:
  BS_USERNAME: ${{ secrets.BS_USERNAME }}
  BS_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}
  ANDROID_APP_CUSTOM_ID: 'ShopperAndroidApp'
  IOS_APP_CUSTOM_ID: 'ShopperIOSApp'
  BUILD_NAME: 'Regression'
  BUILD_TAGS: ${{ inputs.selected_suite }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Install dependencies 📦
        run: npm install

      - name: Run regression tests 🤖
        continue-on-error: true
        env:
          PLATFORM: ${{ inputs.operating_system }}
        shell: bash
        run: |
          chmod +x ./scripts/run_regression_tests.sh
          ./scripts/run_regression_tests.sh "${PLATFORM}" "${BUILD_TAGS}"
  